### ISSUE TITLE
NullInjectorError: No provider for ODataServiceFactory

### ISSUE THREAD

**Issue by SamShekhovtsov** [diegomvh/angular-odata#89]
trying to use this library - angular-odata with the latest Angular 18. 

when executing the code, following strange error is thrown:

`core.mjs:6676 ERROR NullInjectorError: NullInjectorError: No provider for ODataServiceFactory!
    at NullInjector.get (core.mjs:1659:27)
    at R3Injector.get (core.mjs:3105:33)
    at R3Injector.get (core.mjs:3105:33)
    at injectInjectorOnly (core.mjs:1106:40)
    at Module.ɵɵinject (core.mjs:1112:60)`

probably I'm missing something? Or it requries a fix?

**Comment by SamShekhovtsov** [comment]
actually I was missing the module setup configuration:

`ODataModule.forRoot({ config: TheProjectOdataConfig }),`

this bug is resolved.
